#AMHS/SWIM Gateway Test Tool Configuration
#Tue Apr 21 02:38:52 BST 2026
directory.password=secret
swim.test.profile=RABBITMQ
swim.broker.user=default
swim.broker.host=localhost
amqp_broker_profile=SOLACE
swim.broker.port=5672
swim.broker.vpn=default
gateway.test_recipient=VVTSYMYX
amhs.channel=default
gateway.default_topic=ALT_TEST_TOPIC
gateway.default_queue=ALT_TEST_QUEUE
swim.container.id=amhs-swim-gateway-test
gateway.max_size=1000000
directory.host=ldap\://localhost\:389
swim.broker.password=default
amhs.mta.port=10000
gateway.default_originator=LFRCZZZZ
amhs.mta.host=localhost
directory.dn=cn\=admin
gateway.max_recipients=512
