#AMHS/SWIM Gateway Test Tool Configuration
#Fri Jul 17 14:49:44 ICT 2026
directory.password=secret
swim.test.profile=RABBITMQ
swim.broker.user=default
swim.broker.host=192.168.22.163
amqp_broker_profile=SOLACE
swim.broker.port=5672
swim.broker.vpn=default
gateway.test_recipient=VVTSYMYX
amhs.channel=default
gateway.default_topic=ats/fpl/flightplan
gateway.default_queue=ats/fpl/flightplan
swim.container.id=amhs-swim-gateway-test
gateway.max_size=1000000
directory.host=ldap\://localhost\:389
swim.broker.password=default
auto_send.interval_seconds=5
amhs.mta.port=10000
gateway.default_originator=VVTSSWIM
amhs.mta.host=localhost
directory.dn=cn\=admin
gateway.max_recipients=512
auto_send.enabled=true
