#AMHS/SWIM Gateway Test Tool Configuration
#Tue Apr 07 04:27:49 BST 2026
directory.password=secret
swim.test.profile=RABBITMQ
swim.broker.user=default
swim.broker.host=localhost
swim.broker.port=5672
swim.broker.vpn=default
amhs.channel=default
swim.container.id=amhs-swim-gateway-test
gateway.max_size=1000000
directory.host=ldap\://localhost\:389
swim.broker.password=default
amhs.mta.port=10000
amhs.mta.host=localhost
directory.dn=cn\=admin
gateway.max_recipients=512
